from PySide6.QtCore import Signal
from ..localization import Translator
from PySide6.QtWidgets import (QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
                              QLabel, QComboBox, QPushButton, QLineEdit, QCheckBox, QTabWidget, QScrollArea)


class MainWindow(QMainWindow):
    close_requested = Signal()

    def __init__(self, settings, icon):
        super().__init__()
        self.translator = Translator(settings.language)
        self.setWindowTitle(self.t("window.title"))
        self.setWindowIcon(icon)
        self.resize(740, 460)
        body = QWidget()
        self.tabs = QTabWidget()
        self.setCentralWidget(self.tabs)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(body)
        self.tabs.addTab(scroll,self.t("tab.recording"))
        layout = QVBoxLayout(body)
        title = QLabel(self.t("recording.title"))
        title.setStyleSheet("font-size: 24px; font-weight: bold")
        layout.addWidget(title)
        layout.addWidget(QLabel(self.t("recording.description")))
        self.source_mode = QComboBox()
        for key, label in (("monitor",self.t("source.monitor")), ("region",self.t("source.region")), ("window",self.t("source.window")), ("tab",self.t("source.tab"))):
            self.source_mode.addItem(label, key)
        self.source_mode.setCurrentIndex(max(0, self.source_mode.findData(settings.source_mode)))
        layout.addWidget(QLabel(self.t("source.label")))
        layout.addWidget(self.source_mode)
        row = QHBoxLayout()
        self.monitors = QComboBox()
        self.window_list = QComboBox()
        row.addWidget(self.window_list, 1)
        self.refresh = QPushButton(self.t("sources.refresh"))
        row.addWidget(self.monitors, 1)
        row.addWidget(self.refresh)
        layout.addLayout(row)
        row = QHBoxLayout()
        self.select_region = QPushButton(self.t("region.select"))
        self.region_info = QLabel()
        layout.addWidget(self.select_region)
        layout.addWidget(self.region_info)
        self.tab_panel = QWidget()
        tab_layout = QVBoxLayout(self.tab_panel)
        hint = QLabel(self.t("tab.hint"))
        hint.setWordWrap(True)
        tab_layout.addWidget(hint)
        self.export_extension = QPushButton(self.t("extension.save"))
        tab_layout.addWidget(self.export_extension)
        self.pairing = QLineEdit()
        self.pairing.setReadOnly(True)
        self.pairing.setPlaceholderText(self.t("pairing.placeholder"))
        tab_layout.addWidget(self.pairing)
        self.copy_pairing = QPushButton(self.t("pairing.copy"))
        tab_layout.addWidget(self.copy_pairing)
        layout.addWidget(self.tab_panel)
        self.folder = QLineEdit(settings.output_dir)
        self.folder.setReadOnly(True)
        self.browse = QPushButton(self.t("folder.choose"))
        row.addWidget(self.folder, 1)
        row.addWidget(self.browse)
        layout.addLayout(row)
        row = QHBoxLayout()
        row.addWidget(QLabel(self.t("fps.label")))
        self.fps = QComboBox()
        self.fps.addItems(["15", "24", "30", "60"])
        self.fps.setCurrentText(str(settings.fps))
        row.addWidget(self.fps)
        row.addStretch()
        layout.addLayout(row)
        self.configure = QPushButton(self.t("settings.recording"))
        layout.addWidget(self.configure)
        self.filename_button = QPushButton(self.t("settings.filename"))
        layout.addWidget(self.filename_button)
        self.overlay_button = QPushButton(self.t("settings.overlay"))
        self.overlay_enabled = QCheckBox(self.t("overlay.enabled"))
        self.overlay_enabled.setChecked(settings.overlay_enabled)
        layout.addWidget(self.overlay_button)
        layout.addWidget(self.overlay_enabled)
        self.recording_summary = QLabel()
        self.recording_summary.setWordWrap(True)
        layout.addWidget(self.recording_summary)
        self.close_to_tray = QCheckBox(self.t("tray.close"))
        self.close_to_tray.setChecked(settings.close_to_tray)
        layout.addWidget(self.close_to_tray)
        self.status = QLabel(self.t("status.ready"))
        self.status.setWordWrap(True)
        layout.addWidget(self.status)
        row = QHBoxLayout()
        self.start = QPushButton(self.t("action.start"))
        self.stop = QPushButton(self.t("action.stop"))
        self.stop.setEnabled(False)
        self.open_folder = QPushButton(self.t("folder.open"))
        row.addWidget(self.start)
        row.addWidget(self.stop)
        row.addWidget(self.open_folder)
        layout.addLayout(row)
        layout.addWidget(QLabel(self.t("recording.modes")))

        from .recordings_view import RecordingsView
        self.recordings = RecordingsView(settings.output_dir, language=settings.language)
        self.tabs.addTab(self.recordings,self.t("tab.recordings"))
        self.tabs.currentChanged.connect(lambda index: self.recordings.activate() if index == 1 else self.recordings.stop_playback())

    def t(self, key):
        return self.translator.tr(key)

    def closeEvent(self, event):
        event.ignore()
        self.close_requested.emit()
