from PySide6.QtCore import Signal
from PySide6.QtWidgets import (QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
                              QLabel, QComboBox, QPushButton, QLineEdit, QCheckBox, QTabWidget, QScrollArea)


class MainWindow(QMainWindow):
    close_requested = Signal()

    def __init__(self, settings, icon):
        super().__init__()
        self.setWindowTitle("ScreenRec — запись экрана")
        self.setWindowIcon(icon)
        self.resize(740, 460)
        body = QWidget()
        self.tabs = QTabWidget()
        self.setCentralWidget(self.tabs)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(body)
        self.tabs.addTab(scroll,"Запись")
        layout = QVBoxLayout(body)
        title = QLabel("Запись экрана")
        title.setStyleSheet("font-size: 24px; font-weight: bold")
        layout.addWidget(title)
        layout.addWidget(QLabel("Выберите источник и папку для сохранения записи."))
        self.source_mode = QComboBox()
        for key, label in (("monitor","Монитор"), ("region","Область экрана"), ("window","Окно программы"), ("tab","Вкладка браузера")):
            self.source_mode.addItem(label, key)
        self.source_mode.setCurrentIndex(max(0, self.source_mode.findData(settings.source_mode)))
        layout.addWidget(QLabel("Источник записи:"))
        layout.addWidget(self.source_mode)
        row = QHBoxLayout()
        self.monitors = QComboBox()
        self.window_list = QComboBox()
        row.addWidget(self.window_list, 1)
        self.refresh = QPushButton("Обновить источники")
        row.addWidget(self.monitors, 1)
        row.addWidget(self.refresh)
        layout.addLayout(row)
        row = QHBoxLayout()
        self.select_region = QPushButton("Выделить область мышью…")
        self.region_info = QLabel()
        layout.addWidget(self.select_region)
        layout.addWidget(self.region_info)
        self.tab_panel = QWidget()
        tab_layout = QVBoxLayout(self.tab_panel)
        hint = QLabel("Нажмите «Начать запись», скопируйте код и подключите нужную вкладку через расширение Chrome/Edge.")
        hint.setWordWrap(True)
        tab_layout.addWidget(hint)
        self.export_extension = QPushButton("Сохранить расширение для установки…")
        tab_layout.addWidget(self.export_extension)
        self.pairing = QLineEdit()
        self.pairing.setReadOnly(True)
        self.pairing.setPlaceholderText("Код появится после начала сеанса")
        tab_layout.addWidget(self.pairing)
        self.copy_pairing = QPushButton("Скопировать код подключения")
        tab_layout.addWidget(self.copy_pairing)
        layout.addWidget(self.tab_panel)
        self.folder = QLineEdit(settings.output_dir)
        self.folder.setReadOnly(True)
        self.browse = QPushButton("Выбрать папку…")
        row.addWidget(self.folder, 1)
        row.addWidget(self.browse)
        layout.addLayout(row)
        row = QHBoxLayout()
        row.addWidget(QLabel("Кадров в секунду:"))
        self.fps = QComboBox()
        self.fps.addItems(["15", "24", "30", "60"])
        self.fps.setCurrentText(str(settings.fps))
        row.addWidget(self.fps)
        row.addStretch()
        layout.addLayout(row)
        self.configure = QPushButton("Конфигуратор записи…")
        layout.addWidget(self.configure)
        self.filename_button = QPushButton("Имя файла…")
        layout.addWidget(self.filename_button)
        self.overlay_button = QPushButton("Картинка и текст…")
        self.overlay_enabled = QCheckBox("Накладывать картинку / текст")
        self.overlay_enabled.setChecked(settings.overlay_enabled)
        layout.addWidget(self.overlay_button)
        layout.addWidget(self.overlay_enabled)
        self.recording_summary = QLabel()
        self.recording_summary.setWordWrap(True)
        layout.addWidget(self.recording_summary)
        self.close_to_tray = QCheckBox("Сворачивать в трей при закрытии")
        self.close_to_tray.setChecked(settings.close_to_tray)
        layout.addWidget(self.close_to_tray)
        self.status = QLabel("Готов к записи")
        self.status.setWordWrap(True)
        layout.addWidget(self.status)
        row = QHBoxLayout()
        self.start = QPushButton("Начать запись")
        self.stop = QPushButton("Остановить")
        self.stop.setEnabled(False)
        self.open_folder = QPushButton("Открыть папку")
        row.addWidget(self.start)
        row.addWidget(self.stop)
        row.addWidget(self.open_folder)
        layout.addLayout(row)
        layout.addWidget(QLabel("Монитор • область • окно • вкладка"))

        from .recordings_view import RecordingsView
        self.recordings = RecordingsView(settings.output_dir)
        self.tabs.addTab(self.recordings,"Записи")
        self.tabs.currentChanged.connect(lambda index: self.recordings.activate() if index == 1 else self.recordings.stop_playback())

    def closeEvent(self, event):
        event.ignore()
        self.close_requested.emit()
